package com.example.demo.controller;

import com.example.demo.entity.Product;
import com.example.demo.entity.Supplier;
import com.example.demo.repository.ProductRepository;
import com.example.demo.repository.SupplierRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.http.ResponseEntity;

import java.util.List;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /api (after Application path)
public class MainController {
    @Autowired // This means to get the bean called supplierRepository.Which is auto-generated by Spring, we will use it to handle the data
    private SupplierRepository supplierRepository;

    @Autowired // This means to get the bean called supplierRepository. Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository productRepository;

    // Get all Suppliers
    @GetMapping("/getSuppliers")
    public ResponseEntity<?> getSuppliers() {
        // This returns a JSON or XML with the users
        List<Supplier> supplierList = supplierRepository.findAll();
        return ResponseEntity.ok().body(supplierRepository.findAll());
    }

    // Get all Products
    @GetMapping("/getProducts")
    public List<Product> getProducts() {
        return this.productRepository.findAll();
    }
}
